# Generated by Django 3.2.6 on 2021-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
