# Generated by Django 3.2.6 on 2021-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210824_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(default='color'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.TextField(default='manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(default='material'),
        ),
    ]
