# Generated by Django 3.2.6 on 2021-08-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210825_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.TextField(default='https://static.onlinetrade.ru/img/items/b/1348575_1.jpg'),
        ),
    ]
