# Generated by Django 3.2.6 on 2021-08-26 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Время создания записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='update_on',
            field=models.DateTimeField(auto_now=True, help_text='Время обновления записи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(default='category', help_text='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.TextField(default='color', help_text='Цвет товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='description', help_text='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.TextField(default='.', help_text='Ссылка на фото товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.TextField(default='manufacturer', help_text='Производитель товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.TextField(default='material', help_text='Материал товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(default='name', help_text='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, help_text='Цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.IntegerField(default=0, help_text='Количество товара'),
        ),
    ]
